[package]
name = "openat"
description = """
    A wrapper around openat, symlinkat, and similar system calls
"""
license = "MIT/Apache-2.0"
readme = "README.rst"
keywords = ["open", "openat", "filesystem", "fs"]
homepage = "http://github.com/tailhook/openat"
documentation = "http://docs.rs/openat"
version = "0.1.3"
authors = ["paul@colomiets.name"]

[dependencies]
libc = "0.2.18"
